server:
  port: 8088
  context-path: /hi

spring:
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 654321
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 39.108.160.171
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.*.model

#pagehelper插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

