
package mdm_web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IMdSharingCenterService", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", wsdlLocation = "http://128.14.1.66:809/uapws/service/com.yonyou.itf.mdm07.sharing.IMdSharingCenterService?wsdl")
public class IMdSharingCenterService
    extends Service
{

    private final static URL IMDSHARINGCENTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMDSHARINGCENTERSERVICE_EXCEPTION;
    private final static QName IMDSHARINGCENTERSERVICE_QNAME = new QName("http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", "IMdSharingCenterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://128.14.1.66:809/uapws/service/com.yonyou.itf.mdm07.sharing.IMdSharingCenterService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMDSHARINGCENTERSERVICE_WSDL_LOCATION = url;
        IMDSHARINGCENTERSERVICE_EXCEPTION = e;
    }

    public IMdSharingCenterService() {
        super(__getWsdlLocation(), IMDSHARINGCENTERSERVICE_QNAME);
    }

    public IMdSharingCenterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMDSHARINGCENTERSERVICE_QNAME, features);
    }

    public IMdSharingCenterService(URL wsdlLocation) {
        super(wsdlLocation, IMDSHARINGCENTERSERVICE_QNAME);
    }

    public IMdSharingCenterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMDSHARINGCENTERSERVICE_QNAME, features);
    }

    public IMdSharingCenterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMdSharingCenterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMdSharingCenterServicePortType
     */
    @WebEndpoint(name = "IMdSharingCenterServiceSOAP11port_http")
    public IMdSharingCenterServicePortType getIMdSharingCenterServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", "IMdSharingCenterServiceSOAP11port_http"), IMdSharingCenterServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMdSharingCenterServicePortType
     */
    @WebEndpoint(name = "IMdSharingCenterServiceSOAP11port_http")
    public IMdSharingCenterServicePortType getIMdSharingCenterServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", "IMdSharingCenterServiceSOAP11port_http"), IMdSharingCenterServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMDSHARINGCENTERSERVICE_EXCEPTION!= null) {
            throw IMDSHARINGCENTERSERVICE_EXCEPTION;
        }
        return IMDSHARINGCENTERSERVICE_WSDL_LOCATION;
    }

}
